export interface MusicItem {
  id: string;
  title: string;
  artist: string;
  album?: string;
  durationText?: string;
  durationSeconds?: number;
  thumbnail: string;
  type: 'song' | 'video' | 'album' | 'artist' | 'playlist';
  isTopResult?: boolean;
}

export interface CountryCatalogData {
  countryCode: string;
  countryName: string;
  flag: string;
  genre: string;
  description: string;
  tracks: MusicItem[];
}

export const COUNTRY_CATALOG: Record<string, CountryCatalogData> = {
  IN: {
    countryCode: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    genre: 'Bollywood & Indian Pop',
    description: 'Trending Bollywood hits, Punjabi chartbusters, and romantic melodies across India.',
    tracks: [
      {
        id: 'VAdGW7QDJUI',
        title: 'Chaleya (From "Jawan")',
        artist: 'Arijit Singh, Shilpa Rao, Anirudh Ravichander',
        album: 'Jawan',
        durationText: '3:20',
        durationSeconds: 200,
        thumbnail: 'https://i.ytimg.com/vi/VAdGW7QDJUI/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'BddP6PYo2gs',
        title: 'Kesariya (From "Brahmastra")',
        artist: 'Pritam, Arijit Singh, Amitabh Bhattacharya',
        album: 'Brahmastra',
        durationText: '4:28',
        durationSeconds: 268,
        thumbnail: 'https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'mH_LFkW_JGs',
        title: 'Lover',
        artist: 'Diljit Dosanjh',
        album: 'MoonChild Era',
        durationText: '3:15',
        durationSeconds: 195,
        thumbnail: 'https://i.ytimg.com/vi/mH_LFkW_JGs/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'ElZfdU54Cp8',
        title: 'Apna Bana Le (From "Bhediya")',
        artist: 'Arijit Singh, Sachin-Jigar',
        album: 'Bhediya',
        durationText: '4:21',
        durationSeconds: 261,
        thumbnail: 'https://i.ytimg.com/vi/ElZfdU54Cp8/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'IJq0yyWug1k',
        title: 'Tum Hi Ho (From "Aashiqui 2")',
        artist: 'Arijit Singh, Mithoon',
        album: 'Aashiqui 2',
        durationText: '4:22',
        durationSeconds: 262,
        thumbnail: 'https://i.ytimg.com/vi/IJq0yyWug1k/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'gvyUuxdRdR4',
        title: 'Raataan Lambiyan (From "Shershaah")',
        artist: 'Tanishk Bagchi, Jubin Nautiyal, Asees Kaur',
        album: 'Shershaah',
        durationText: '3:50',
        durationSeconds: 230,
        thumbnail: 'https://i.ytimg.com/vi/gvyUuxdRdR4/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'VNs_cCtdbPc',
        title: 'Brown Munde',
        artist: 'AP Dhillon, Gurinder Gill, Shinda Kahlon',
        album: 'Brown Munde',
        durationText: '4:06',
        durationSeconds: 246,
        thumbnail: 'https://i.ytimg.com/vi/VNs_cCtdbPc/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'JGwWNGJdvx8',
        title: 'Shape of You',
        artist: 'Ed Sheeran',
        album: '÷ (Divide)',
        durationText: '4:24',
        durationSeconds: 264,
        thumbnail: 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  US: {
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    genre: 'Billboard Hot 100 & Pop',
    description: 'The biggest streaming hits, viral Billboard tracks, and pop anthems in the US right now.',
    tracks: [
      {
        id: 'xF-0mH7831k',
        title: 'Espresso',
        artist: 'Sabrina Carpenter',
        album: 'Short n\' Sweet',
        durationText: '2:55',
        durationSeconds: 175,
        thumbnail: 'https://i.ytimg.com/vi/xF-0mH7831k/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'ic8j13piAhQ',
        title: 'Cruel Summer',
        artist: 'Taylor Swift',
        album: 'Lover',
        durationText: '2:58',
        durationSeconds: 178,
        thumbnail: 'https://i.ytimg.com/vi/ic8j13piAhQ/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '4NRXx6U8ABQ',
        title: 'Blinding Lights',
        artist: 'The Weeknd',
        album: 'After Hours',
        durationText: '3:20',
        durationSeconds: 200,
        thumbnail: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'H58vbez_m4E',
        title: 'Not Like Us',
        artist: 'Kendrick Lamar',
        album: 'Not Like Us',
        durationText: '4:34',
        durationSeconds: 274,
        thumbnail: 'https://i.ytimg.com/vi/H58vbez_m4E/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'd5gf9dXHeG4',
        title: 'BIRDS OF A FEATHER',
        artist: 'Billie Eilish',
        album: 'HIT ME HARD AND SOFT',
        durationText: '3:30',
        durationSeconds: 210,
        thumbnail: 'https://i.ytimg.com/vi/d5gf9dXHeG4/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '4QIZC483ihs',
        title: 'I Had Some Help',
        artist: 'Post Malone ft. Morgan Wallen',
        album: 'F-1 Trillion',
        durationText: '2:58',
        durationSeconds: 178,
        thumbnail: 'https://i.ytimg.com/vi/4QIZC483ihs/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'm4_9TFeMfJE',
        title: 'Paint The Town Red',
        artist: 'Doja Cat',
        album: 'Scarlet',
        durationText: '3:51',
        durationSeconds: 231,
        thumbnail: 'https://i.ytimg.com/vi/m4_9TFeMfJE/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '7wtfhZwyrcc',
        title: 'Believer',
        artist: 'Imagine Dragons',
        album: 'Evolve',
        durationText: '3:24',
        durationSeconds: 204,
        thumbnail: 'https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  GB: {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    genre: 'UK Singles Chart & Indie',
    description: 'Top tracks across London, Manchester, and the UK Official Charts.',
    tracks: [
      {
        id: 'H5v3kku4y6Q',
        title: 'As It Was',
        artist: 'Harry Styles',
        album: 'Harry\'s House',
        durationText: '2:47',
        durationSeconds: 167,
        thumbnail: 'https://i.ytimg.com/vi/H5v3kku4y6Q/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'TUVcZfQe-Kw',
        title: 'Levitating',
        artist: 'Dua Lipa',
        album: 'Future Nostalgia',
        durationText: '3:23',
        durationSeconds: 203,
        thumbnail: 'https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'JGwWNGJdvx8',
        title: 'Shape of You',
        artist: 'Ed Sheeran',
        album: '÷ (Divide)',
        durationText: '4:24',
        durationSeconds: 264,
        thumbnail: 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'OiC1rgCPmUQ',
        title: 'Dance The Night',
        artist: 'Dua Lipa',
        album: 'Barbie The Album',
        durationText: '2:56',
        durationSeconds: 176,
        thumbnail: 'https://i.ytimg.com/vi/OiC1rgCPmUQ/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'zABLecsR5UE',
        title: 'Someone You Loved',
        artist: 'Lewis Capaldi',
        album: 'Divinely Uninspired',
        durationText: '3:02',
        durationSeconds: 182,
        thumbnail: 'https://i.ytimg.com/vi/zABLecsR5UE/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'YQHsXMglC9A',
        title: 'Hello',
        artist: 'Adele',
        album: '25',
        durationText: '4:55',
        durationSeconds: 295,
        thumbnail: 'https://i.ytimg.com/vi/YQHsXMglC9A/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  BR: {
    countryCode: 'BR',
    countryName: 'Brazil',
    flag: '🇧🇷',
    genre: 'Sertanejo, Funk & Brazilian Pop',
    description: 'Os maiores sucessos do Brasil: funk carioca, sertanejo universitário e pop brasileiro.',
    tracks: [
      {
        id: 'saqcwGvHj4E',
        title: 'Envolver',
        artist: 'Anitta',
        album: 'Versions of Me',
        durationText: '3:13',
        durationSeconds: 193,
        thumbnail: 'https://i.ytimg.com/vi/saqcwGvHj4E/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '3M5mXk6WwQc',
        title: 'Leão',
        artist: 'Marília Mendonça',
        album: 'Decretos Reais',
        durationText: '2:46',
        durationSeconds: 166,
        thumbnail: 'https://i.ytimg.com/vi/3M5mXk6WwQc/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'G9oO5jI5H40',
        title: 'Nosso Quadro',
        artist: 'Ana Castela',
        album: 'Boiadeira',
        durationText: '2:53',
        durationSeconds: 173,
        thumbnail: 'https://i.ytimg.com/vi/G9oO5jI5H40/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'kJQP7kiw5Fk',
        title: 'Despacito',
        artist: 'Luis Fonsi ft. Daddy Yankee',
        album: 'Vida',
        durationText: '4:42',
        durationSeconds: 282,
        thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  MX: {
    countryCode: 'MX',
    countryName: 'Mexico',
    flag: '🇲🇽',
    genre: 'Regional Mexican & Latin Urban',
    description: 'Los temas más escuchados en México: corridos tumbados, reggaetón y éxitos latinos.',
    tracks: [
      {
        id: 'lZ1AT_sM6fA',
        title: 'Ella Baila Sola',
        artist: 'Eslabon Armado, Peso Pluma',
        album: 'Desvelado',
        durationText: '2:45',
        durationSeconds: 165,
        thumbnail: 'https://i.ytimg.com/vi/lZ1AT_sM6fA/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '_XbgXdeqi4Y',
        title: 'MONACO',
        artist: 'Bad Bunny',
        album: 'Nadie Sabe Lo Que Va A Pasar Mañana',
        durationText: '4:27',
        durationSeconds: 267,
        thumbnail: 'https://i.ytimg.com/vi/_XbgXdeqi4Y/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '1oXoE5M7Wyc',
        title: 'QLONA',
        artist: 'KAROL G, Peso Pluma',
        album: 'MAÑANA SERÁ BONITO',
        durationText: '2:52',
        durationSeconds: 172,
        thumbnail: 'https://i.ytimg.com/vi/1oXoE5M7Wyc/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'kJQP7kiw5Fk',
        title: 'Despacito',
        artist: 'Luis Fonsi ft. Daddy Yankee',
        album: 'Vida',
        durationText: '4:42',
        durationSeconds: 282,
        thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  NG: {
    countryCode: 'NG',
    countryName: 'Nigeria',
    flag: '🇳🇬',
    genre: 'Afrobeats & Afro-Pop',
    description: 'Global Afrobeats, Naija chart-toppers, and Amapiano energy straight from Lagos.',
    tracks: [
      {
        id: 'CQLsdmU420g',
        title: 'Calm Down',
        artist: 'Rema',
        album: 'Rave & Climax',
        durationText: '3:39',
        durationSeconds: 219,
        thumbnail: 'https://i.ytimg.com/vi/CQLsdmU420g/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '42TK88w5Z1A',
        title: 'Last Last',
        artist: 'Burna Boy',
        album: 'Love, Damini',
        durationText: '2:52',
        durationSeconds: 172,
        thumbnail: 'https://i.ytimg.com/vi/42TK88w5Z1A/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'XoiOOiuH8iI',
        title: 'Water',
        artist: 'Tyla',
        album: 'TYLA',
        durationText: '3:20',
        durationSeconds: 200,
        thumbnail: 'https://i.ytimg.com/vi/XoiOOiuH8iI/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'OSCarvgZtEQ',
        title: 'UNAVAILABLE',
        artist: 'Davido ft. Musa Keys',
        album: 'Timeless',
        durationText: '2:50',
        durationSeconds: 170,
        thumbnail: 'https://i.ytimg.com/vi/OSCarvgZtEQ/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  JP: {
    countryCode: 'JP',
    countryName: 'Japan',
    flag: '🇯🇵',
    genre: 'J-Pop & Anime Soundtracks',
    description: '日本の最新ヒットチャート：アニメ主題歌、J-POP、バイラルヒット曲。',
    tracks: [
      {
        id: 'ZRtdQ81jPUQ',
        title: 'アイドル (Idol)',
        artist: 'YOASOBI',
        album: 'Oshi no Ko OP',
        durationText: '3:33',
        durationSeconds: 213,
        thumbnail: 'https://i.ytimg.com/vi/ZRtdQ81jPUQ/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'M2cckDmNLMI',
        title: 'KICK BACK',
        artist: 'Kenshi Yonezu',
        album: 'Chainsaw Man OP',
        durationText: '3:13',
        durationSeconds: 193,
        thumbnail: 'https://i.ytimg.com/vi/M2cckDmNLMI/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'dFf4AgBNR1E',
        title: 'Shinunoga E-Wa',
        artist: 'Fujii Kaze',
        album: 'HELP EVER HURT NEVER',
        durationText: '3:05',
        durationSeconds: 185,
        thumbnail: 'https://i.ytimg.com/vi/dFf4AgBNR1E/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'pgXpM4l_MwI',
        title: '唱 (Show)',
        artist: 'Ado',
        album: 'Universal Studios Japan collab',
        durationText: '3:11',
        durationSeconds: 191,
        thumbnail: 'https://i.ytimg.com/vi/pgXpM4l_MwI/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  KR: {
    countryCode: 'KR',
    countryName: 'South Korea',
    flag: '🇰🇷',
    genre: 'K-Pop & Korean R&B',
    description: '대한민국 및 글로벌 K-Pop 차트 1위 곡과 트렌딩 음원.',
    tracks: [
      {
        id: 'QU9c0053UAU',
        title: 'Seven (feat. Latto)',
        artist: 'Jung Kook',
        album: 'GOLDEN',
        durationText: '3:04',
        durationSeconds: 184,
        thumbnail: 'https://i.ytimg.com/vi/QU9c0053UAU/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'ArmDp-zijuc',
        title: 'Super Shy',
        artist: 'NewJeans',
        album: 'Get Up',
        durationText: '2:34',
        durationSeconds: 154,
        thumbnail: 'https://i.ytimg.com/vi/ArmDp-zijuc/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'gdZLi9oWNZg',
        title: 'Dynamite',
        artist: 'BTS',
        album: 'BE',
        durationText: '3:19',
        durationSeconds: 199,
        thumbnail: 'https://i.ytimg.com/vi/gdZLi9oWNZg/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'ioNng23DkIM',
        title: 'How You Like That',
        artist: 'BLACKPINK',
        album: 'THE ALBUM',
        durationText: '3:01',
        durationSeconds: 181,
        thumbnail: 'https://i.ytimg.com/vi/ioNng23DkIM/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  DE: {
    countryCode: 'DE',
    countryName: 'Germany',
    flag: '🇩🇪',
    genre: 'German Rap & European Dance',
    description: 'Die angesagtesten Tracks in Deutschland: Deutschrap, Pop und Club-Hits.',
    tracks: [
      {
        id: 'hD3sM_rU3K4',
        title: 'Komet',
        artist: 'Udo Lindenberg & Apache 207',
        album: 'Komet',
        durationText: '2:47',
        durationSeconds: 167,
        thumbnail: 'https://i.ytimg.com/vi/hD3sM_rU3K4/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '_y5M8bBv33c',
        title: 'Wildberry Lillet',
        artist: 'Nina Chuba',
        album: 'Glas',
        durationText: '2:11',
        durationSeconds: 131,
        thumbnail: 'https://i.ytimg.com/vi/_y5M8bBv33c/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '4NRXx6U8ABQ',
        title: 'Blinding Lights',
        artist: 'The Weeknd',
        album: 'After Hours',
        durationText: '3:20',
        durationSeconds: 200,
        thumbnail: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  FR: {
    countryCode: 'FR',
    countryName: 'France',
    flag: '🇫🇷',
    genre: 'French Hip-Hop & Chanson Pop',
    description: 'Les plus grands hits en France : rap français, pop urbaine et nouveautés.',
    tracks: [
      {
        id: 'iPGgnzc34tY',
        title: 'Djadja',
        artist: 'Aya Nakamura',
        album: 'NAKAMURA',
        durationText: '2:51',
        durationSeconds: 171,
        thumbnail: 'https://i.ytimg.com/vi/iPGgnzc34tY/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'VHoT4N43jK8',
        title: 'Alors on danse',
        artist: 'Stromae',
        album: 'Cheese',
        durationText: '3:25',
        durationSeconds: 205,
        thumbnail: 'https://i.ytimg.com/vi/VHoT4N43jK8/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'Fxbm7kCvdG8',
        title: 'Tout oublier',
        artist: 'Angèle ft. Roméo Elvis',
        album: 'Brol',
        durationText: '3:22',
        durationSeconds: 202,
        thumbnail: 'https://i.ytimg.com/vi/Fxbm7kCvdG8/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  PH: {
    countryCode: 'PH',
    countryName: 'Philippines',
    flag: '🇵🇭',
    genre: 'OPM & P-Pop',
    description: 'Top Pinoy hits, P-Pop sensations, and beloved OPM acoustic anthems in the Philippines.',
    tracks: [
      {
        id: 'O48b_wW2k0Y',
        title: 'Pantropiko',
        artist: 'BINI',
        album: 'Talaarawan',
        durationText: '3:45',
        durationSeconds: 225,
        thumbnail: 'https://i.ytimg.com/vi/O48b_wW2k0Y/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'VJ5hD_K_7h8',
        title: 'GENTO',
        artist: 'SB19',
        album: 'PAGTATAG!',
        durationText: '3:52',
        durationSeconds: 232,
        thumbnail: 'https://i.ytimg.com/vi/VJ5hD_K_7h8/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'L4c8v0M8e4U',
        title: 'Raining In Manila',
        artist: 'Lola Amour',
        album: 'Raining In Manila',
        durationText: '4:50',
        durationSeconds: 290,
        thumbnail: 'https://i.ytimg.com/vi/L4c8v0M8e4U/hqdefault.jpg',
        type: 'song',
      }
    ],
  },
  ID: {
    countryCode: 'ID',
    countryName: 'Indonesia',
    flag: '🇮🇩',
    genre: 'Indonesian Pop & Dangdut',
    description: 'Lagu-lagu terpopuler di Indonesia: pop galau, viral TikTok, dan tembang hits tanah air.',
    tracks: [
      {
        id: 'Xb5w6y7z8a9',
        title: 'Sial',
        artist: 'Mahalini',
        album: 'Fábula',
        durationText: '4:03',
        durationSeconds: 243,
        thumbnail: 'https://i.ytimg.com/vi/Xb5w6y7z8a9/hqdefault.jpg',
        type: 'song',
      },
      {
        id: '4NRXx6U8ABQ',
        title: 'Blinding Lights',
        artist: 'The Weeknd',
        album: 'After Hours',
        durationText: '3:20',
        durationSeconds: 200,
        thumbnail: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg',
        type: 'song',
      },
      {
        id: 'JGwWNGJdvx8',
        title: 'Shape of You',
        artist: 'Ed Sheeran',
        album: '÷ (Divide)',
        durationText: '4:24',
        durationSeconds: 264,
        thumbnail: 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg',
        type: 'song',
      }
    ],
  }
};

export const POPULAR_COUNTRIES = [
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' }
];

export function getCountryCatalog(countryCode: string): CountryCatalogData {
  const code = (countryCode || '').toUpperCase();
  if (COUNTRY_CATALOG[code]) {
    return COUNTRY_CATALOG[code];
  }

  // Fallback to US / Global catalog
  return COUNTRY_CATALOG['US'];
}
